### ISSUE TITLE
Tests failed while performing the build

### ISSUE THREAD

**Issue by harshseth** [UglyTroLL/ReKognitionJavaSDK#1]
The error it shows is as follows 
junit.framework.AssertionFailedError: No tests found in com.imjojo.rekognition.<test name>

It failed all the 13 tests.
Eventually it failed to provide me with jars.

**Comment by UglyTroLL** [comment]
As I mentioned in the Readme, https://github.com/UglyTroLL/ReKognitionJavaSDK#examples
All unit tests were disabled (commented out from the code) by default, since most of them need the accessToken and the accessSecret. 
You might want to skip the test by

```
mvn clean install ---Dmaven.test.skip=true
```

when you compile it
